### ISSUE TITLE
Combining meshes & SDFs

### ISSUE THREAD

**Issue by dumblob** [Yeicor/sdfx-ui#1]
I wonder whether this supports "seamless" interoperation between meshes and SDFs.

E.g. if I wanted to improve over existing mesh by adding something to it by using SDFs (because it's probably easier) and then again add something else to these SDFs but in the form of a mesh (because it's easier than to do it with SDFs).

How should I approach it?

**Comment by yeicor** [comment]
> I wonder whether this supports "seamless" interoperation between meshes and SDFs

SDFX already supports this, as this is a core operation not specific to this UI repository.

> if I wanted to improve over existing mesh by adding something to it by using SDFs

Check out [this pull request](https://github.com/deadsy/sdfx/pull/44) that lets you import valid triangle meshes as SDFs for further modification. It also includes [an example](https://github.com/deadsy/sdfx/blob/master/examples/monkey_hat/main.go) of importing and modifying an existing mesh.

> and then again add something else to these SDFs but in the form of a mesh

You can use the [render package](https://github.com/deadsy/sdfx/tree/master/render) to build a mesh for external modification. But be careful: this is a lossy operation. This is mitigated by generating a lot of detail, but that slows down generation and processing.

**Comment by dumblob** [comment]
Wow, that's even better than I expected. Thanks!
