### ISSUE TITLE
cylinder_head example is slow 

### ISSUE THREAD

**Issue by joeblew99** [Yeicor/sdfx-ui#6]
``` 
go install github.com/Yeicor/sdfx-ui/examples/cylinder_head@latest
go: downloading github.com/Yeicor/sdfx-ui v0.0.0-20220329183229-9d0a5916e683
go: downloading github.com/deadsy/sdfx v0.0.0-20220211044058-15587d44f9eb
go: downloading github.com/hajimehoshi/ebiten v1.12.12
go: downloading github.com/barkimedes/go-deepcopy v0.0.0-20200817023428-a044a1957ca4
go: downloading github.com/fogleman/fauxgl v0.0.0-20200818143847-27cddc103802
go: downloading github.com/subchen/go-trylock/v2 v2.0.0
go: downloading github.com/ajstarks/svgo v0.0.0-20211024235047-1546f124cd8b
go: downloading github.com/llgcode/draw2d v0.0.0-20210904075650-80aa0a2a901d
go: downloading github.com/fogleman/simplify v0.0.0-20170216171241-d32f302d5046
➜  cylinder_head
2022/03/31 09:10:05 [DevRenderer] Rendering 3D mesh...
2022/03/31 09:10:06 [DevRenderer] Mesh is ready
2022/03/31 09:10:06 Error watching file main.go - lstat main.go: no such file or directory
2022/03/31 09:10:09 [DevRenderer] CPU Render took: 13.294702ms - Sending to GPU took: 14.170165ms
2022/03/31 09:10:32 [DevRenderer] CPU Render took: 21.760353ms - Sending to GPU took: 268.14µs
2022/03/31 09:10:35 [DevRenderer] CPU Render took: 30.90263ms - Sending to GPU took: 4.056608ms
``` 

The gui is not usable. Its like a still image.

![Screenshot 2022-03-31 at 09 12 39](https://user-images.githubusercontent.com/11999859/160998432-3b693a0f-b810-423b-b3a1-faa86d686427.png)

``` 
go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/apple/Library/Caches/go-build"
GOENV="/Users/apple/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/apple/workspace/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/apple/workspace/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/opt/go/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/go-build55018952=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by yeicor** [comment]
If what you are experiencing is a complete freeze of the program (it stops responding to any input), it is most likely a deadlock. I checked for races (with go build -race), but AFAIK there is no easy way to fix deadlocks (on a subset of goroutines) until they happen.

Unfortunately, it works on my machine™, so I am going to need more help from you. You could debug the program yourself, pause execution after the freeze and check which goroutines are waiting on each other.

**Comment by joeblew99** [comment]
yes it is a complete freeze ...

what machine are you on ?

**Comment by yeicor** [comment]
Distro: Manjaro Linux Kernel: 5.15.28-1-MANJARO arch: x86_64 bits: 64 Desktop: KDE Plasma v: 5.24.3 
CPU: 6-core Intel Core i7-9750H (-MT MCP-) min/max: 800/4500 MHz

The debugging task mentioned above should be quite easy if you are using an IDE and would probably allow me to fix the problem. Feel free to ask if you need help with it.

**Comment by joeblew99** [comment]
Yeah i need help - thanks for offering to help. Not sure how to debug this...

i am on Mac and use VScode and go 1.8.

**Comment by yeicor** [comment]
I don't use VS Code, but it was simple enough. I made a little tutorial gif. The steps are as follows:

1. Open the project folder in VS Code with the [Go extension](https://code.visualstudio.com/docs/languages/go) installed.
2. Open to the example file.
3. Go to the Run and debug menu on the left, and press the debug button.
4. The app will start, interact with it to force the freeze. Make sure it is frozen before continuing.
5. Once the app is frozen and unresponsive, press the pause button.
6. Open the call stack on the left to see all alive goroutines.
7. Open each goroutine and send me the contents. You may record a video or send me several screenshots.

![demo-vscode-debug](https://user-images.githubusercontent.com/4929005/161770793-a48bd682-c577-4331-b0e1-425a7c01f60d.gif)

Thanks for your help. There is a lot of information and FAQs at https://github.com/golang/vscode-go/blob/master/docs/debugging.md.

**Comment by yeicor** [comment]
I will close this issue as I am unable to reproduce the problem and there was no response for a while.

If anyone else experiences this and is willing to perform the testing detailed above, feel free to reopen this issue with more information.
